plugins:
  - semantic-release-gitmoji
  - - "@semantic-release/npm"
    - npmPublish: false
      pkgRoot: /Packages/com.nekometer.esnya.esnya-sf-addons
  - "@semantic-release/github"
  - "@semantic-release/git"
